version: '3.8'
services:
  postgres:
    container_name: db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: duc
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5400:5432"
    volumes:
      - duc_db_data:/var/lib/postgresql/duc_db_data

volumes:
  duc_db_data: