version: '3.8'
services:
  postgres:
    container_name: db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: duc
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5440:5432"
    volumes:
      - duc_db_data:/var/lib/postgresql/duc_db_data
  redis:
    container_name: redis
    image: redis:7.4.0-alpine
    ports:
      - "6380:6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass password
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5680:5672
      - 15680:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  duc_db_data:
  redis_data:
  rabbitmq_data: