spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/duc
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      username: username
      password: password

duc:
  service-link: https://api-pdex.gov.cv:8242/t/financas.gov/mfservicesduccreatev3/1.0.3/
  by-rubrica-url: https://gateway-pdex.gov.cv/t/financas.gov/rubricaidduc/1.0.0/processBancaArrayId
  by-transacao-url: https://fcd11ecf-a200-497e-9538-49738ca275b0.mock.pstmn.io/t/financas.gov/mfservicesduccreatev3/1.0.3/postProcessBanca
  token: 160891a0-c761-377a-b922-a39a420929b4
  pEmail: odair.fortes@mf.gov.cv

auth:
  username: admin
  password: 123456789

server:
  error:
    include-message: always
