spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/duc
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: password
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

duc:
  service-link: https://api-pdex.gov.cv:8242/t/financas.gov/mfservicesduccreatev3/1.0.3/
  by-rubrica-url: https://gateway-pdex.gov.cv/t/financas.gov/rubricaidduc/1.0.0/processBancaArrayId
  by-transacao-url: https://fcd11ecf-a200-497e-9538-49738ca275b0.mock.pstmn.io/t/financas.gov/mfservicesduccreatev3/1.0.3/postProcessBanca
  token: 160891a0-c761-377a-b922-a39a420929b4
  pEmail: odair.fortes@mf.gov.cv

strapi:
  url: https://54f1c5a6-ce78-4d6b-b4da-a916fab49484.mock.pstmn.io/graphql

auth:
  username: admin
  password: 123456789

server:
  error:
    include-message: always

logging:
  file:
    name: duc.log
    path: ./log/
